

export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const GET_ALL_TUTORS = 'GET_ALL_TUTORS';

export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';

export const GET_ALL_SUBJECTS = 'GET_ALL_SUBJECTS';

export const GET_ALL_CONTRACTS = 'GET_ALL_CONTRACTS';