export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_ALL_TUTORS = 'GET_ALL_TUTORS';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const GET_ALL_SUBJECTS = 'GET_ALL_SUBJECTS';

export const GET_ALL_CONTRACTS = 'GET_ALL_CONTRACTS';
export const GET_ALL_STUDENT_CONTRACTS = 'GET_ALL_STUDENT_CONTRACTS';
export const GET_TUTOR_CONTRACTS = 'GET_TUTOR_CONTRACT';
export const SET_TUTOR_CONTRACT = 'SET_TUTOR_CONTRACT';
export const SET_STUDENT_CONTRACT = 'SET_STUDENT_CONTRACT';

export const GET_CURRENT_TUTOR = 'GET_CURRENT_TUTOR';
export const SET_DETAIL_CONTRACT = 'SET_DETAIL_CONTRACT';

export const INSERT_TUTOR_SUBJECT = 'INSERT_TUTOR_SUBJECT';
export const DELETE_TUTOR_SUBJECT = 'DELETE_TUTOR_SUBJECT';


export const INSERT_SUBJECT = 'INSERT_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
// export const UPDATE_SUBJECTS_TUTOR = 'UPDATE_SUBJECTS_TUTOR';
// export const GET_TUTOR_SUBJECTS = 'GET_TUTOR_SUBJECTS';
